apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    #service.beta.kubernetes.io/azure-load-balancer-ipv4: 192.168.
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "webapp_subnet"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: Gateway-Guestbook
  annotations:
    alb.networking.azure.io/alb-id: "/subscriptions/19526731-8b70-48b5-9dc9-46a102a6660c/resourceGroups/rg-azugwc-cluster-tst-001/providers/Microsoft.ServiceNetworking/trafficControllers/alb-test"
spec:
  gatewayClassName: azure-alb-external
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: Guestbook-Gateway-Route
spec:
  parentRefs:
    - name: Gateway-Guestbook
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: guestbook-ui
          port: 80
